// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetPersoAnnuaire.Context;

#nullable disable

namespace ProjetPersoAnnuaire.Migrations
{
    [DbContext(typeof(DataContextAnnuaire))]
    [Migration("20231026151631_AddMapped")]
    partial class AddMapped
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetPersoAnnuaire.Models.Departement", b =>
                {
                    b.Property<int>("DepartementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartementID"));

                    b.Property<string>("NomDepartement")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartementID");

                    b.ToTable("Departements");
                });

            modelBuilder.Entity("ProjetPersoAnnuaire.Models.Employe", b =>
                {
                    b.Property<int>("EmployeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeID"));

                    b.Property<int>("DepartementID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteID")
                        .HasColumnType("int");

                    b.Property<string>("TelephoneFixe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephonePortable")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeID");

                    b.HasIndex("DepartementID");

                    b.HasIndex("SiteID");

                    b.ToTable("Employes");
                });

            modelBuilder.Entity("ProjetPersoAnnuaire.Models.Site", b =>
                {
                    b.Property<int>("SiteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiteID"));

                    b.Property<string>("Ville")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SiteID");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("ProjetPersoAnnuaire.Models.Employe", b =>
                {
                    b.HasOne("ProjetPersoAnnuaire.Models.Departement", "Departement")
                        .WithMany("Employes")
                        .HasForeignKey("DepartementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetPersoAnnuaire.Models.Site", "Site")
                        .WithMany("Employes")
                        .HasForeignKey("SiteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departement");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("ProjetPersoAnnuaire.Models.Departement", b =>
                {
                    b.Navigation("Employes");
                });

            modelBuilder.Entity("ProjetPersoAnnuaire.Models.Site", b =>
                {
                    b.Navigation("Employes");
                });
#pragma warning restore 612, 618
        }
    }
}
